### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/hypermodern-python#67]
Just a quick question: why didn't you put on console.py a:
```
if __name__ == "__main__":
    main()
```
Isn't it easier to debug code with that? I don't remember if you mention your IDE in the series but how do you usually start debugging with the code as is?

Kind regards..

**Comment by cjolowicz** [comment]
The updated version will contain this. It will also use `__main__.py` instead of `console.py`, which makes the package runnable using `python -m <package>`. You can see this in [cookiecutter-hypermodern-python](https://github.com/cjolowicz/cookiecutter-hypermodern-python) (work in progress).

I'm not sure I understand the significance for debugging. Could you elaborate? If it's a problem right now, maybe you could point the debugger at the entry point script in the Poetry environment instead, or at a unit test.

**Comment by staticdev** [comment]
I see.. nice! I am excited to see the cookiecutter series. I mention the IDE (in my case VSCode) debugging, setting breakpoints and checking the program during runtime. If there is no main() being actually called, console.py runs and does not do anything. In your new template it is not going to happen anymore. Issue closed, thanks again.
